{% set git_import = "github.com/hashicorp/consul/version" %}
{% set name = "consul" %}
{% set version = "1.14.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f31c105beda8efd65432d5ef1c3e47acb9f64e7db099e67cef3a4cb93b10876b

build:
  number: 0
  script:
    {% set git_import = "github.com/hashicorp/consul/version" %}
    - go install -v -ldflags "-X {{ git_import }}.GitDescribe='v{{ version }}'" .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  commands:
    - consul --version

about:
  home: https://www.consul.io
  license: BUSL-1.1
  license_file: LICENSE
  summary: Connect and configure applications across dynamic, distributed infrastructure.
  description: |
    Consul is a distributed, highly available, and data center aware solution to
    connect and configure applications across dynamic, distributed infrastructure.
  doc_url: https://www.consul.io/docs

extra:
  recipe-maintainers:
    - sodre
    - jonashaag
