{% set import_path = "github.com/hashicorp/consul" %}
{% set version = "1.5.2" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = 'src' + os.sep+ import_path.replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: a4d73985748d1bd9a0f4b6deee03eec2201f5afc7ab59579e057b3bdb712284d

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v
        -ldflags "-X {{import_path}}/version.GitRelease='v{{version}}'
                  -X {{import_path}}/version.VersionPrerelease=''"
        .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your
    infrastructure. It provides several key features, including:
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
