{% set git_import = "github.com/hashicorp/consul/version" %}
{% set name = "consul" %}
{% set version = "1.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d71c67c0b3094addfd3aaf27614ebe15f4a6d22f07a6a4db9a0601cef7133583

build:
  number: 0
  script:
    {% set git_import = "github.com/hashicorp/consul/version" %}
    - go install -v -ldflags "-X {{ git_import }}.GitDescribe='v{{ version }}'" .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  requires:
    - gdb
  commands:
    - gdb -ex run -ex bt -ex quit --args consul --version

about:
  home: https://www.consul.io
  license: BUSL-1.1
  license_file: LICENSE
  summary: Connect and configure applications across dynamic, distributed infrastructure.
  description: |
    Consul is a distributed, highly available, and data center aware solution to
    connect and configure applications across dynamic, distributed infrastructure.
  doc_url: https://www.consul.io/docs

extra:
  recipe-maintainers:
    - sodre
    - jonashaag
