{% set name = "consul" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 092fa948012e8f6003211a90af4ae14d1e6c3006535b2bc7eb0eaac34b7f77fb  # [not win]

  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: e5794fc22cd91da3e16af04fc322b82abdc1082cbc022511964277f422325bdb  # [win64]

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}   # [not win]
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - git                    # [not win]
    - make                   # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your 
    infrastructure. It provides several key features, including: 
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and 
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
