{% set git_import = "github.com/hashicorp/consul/version" %}
{% set name = "consul" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: db1cfede52f73038f9f4d87f4698837cf6f7ff3957994dbdce0db78795a081bd

build:
  number: 0
  script:
    {% set git_import = "github.com/hashicorp/consul/version" %}
    - go install -v -ldflags "-X {{ git_import }}.GitDescribe='v{{ version }}'" .

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - consul --version

about:
  home: https://www.consul.io
  license: MPL-2.0
  license_file: LICENSE
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your
    infrastructure. It provides several key features, including:
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
