{% set name = "consul" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5fbf25b8df906dfb4133eedf266a5c4a5af3022428b03a41928e1e48bd59a3b9

build:
  number: 0
  script:
    {% set git_import = "github.com/hashicorp/consul/version" %}
    - go install -v -ldflags "-X {{ git_import }}.GitDescribe='v{{ version }}'" .

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - consul --version | grep -q 'Consul v{{ version }}'  # [unix]
    - consul --version  # [win]

about:
  home: https://www.consul.io
  license: MPL-2.0
  license_file: LICENSE
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your
    infrastructure. It provides several key features, including:
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
