{% set name = "consul" %}
{% set version = "0.9.1" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_386.zip  # [win32]
  fn: {{ name }}-{{ version }}.zip
  sha256: d035207b84c8bd4cdc252b01053d2126b6194e7961a130b11407e6e3a66e4b0e  # [osx]
  sha256: 5143f419b4ba67b6c4fdd023a26a6563f0a7cf47909e648e490ef552caf03f65  # [linux32]
  sha256: e997b87e70dc0f4996d7c5ac89f4776a8569ca99c00e5c8b8a0e0eb1042a9d30  # [linux64]
  sha256: 047117cc205b4541162177684fc1b0f1e6f62b7cae7ea0a3c17ce85afd82df97  # [win32]
  sha256: 74bc3b131411fbcdc650542b94daa28838619c086617ab75c78504eef507e781  # [win64]

build:
  number: {{ build_number }}

test:
  commands:
    - consul -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your 
    infrastructure. It provides several key features, including: 
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and 
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
