appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wciAkbTlI3JbMJ+gq45kVbo2pp2ZnI/cGW8OmF5BbWAx3feZko6T0k2MJVJ0b0x/kH86k5fCFjjuW2j7hxr1gxzIEiX/HQYO6c236gNIVdY6oN8Yd35sf0hKF8QRm44uxwthMxdoGdKqq7kddZEy+n4qtaqt+ZDIVcwlN9W73IzJq8K7BO8JYyvn0segB3JL282Ai7982ZFGexM6MjADut/yr5neZhTOGOwrrqJC7jIuxsnQJDw7lqKChhYrnqTuLv/soepHT8Q1D7qo6252osjDDP1NEwbLVLrUMePNx7C4siI+hBDVRXP2B71tERGPZKyFlMxPA7exjZOCMyLLuU6IYQ+2sgT2slqu9TEJfmHBJgPh3E7kal4ZX5MG3ZGUtXy8S1ne0IByQmOMAp/NSISCnJ/leu0BAlrgrnjPOHx7U6VgzDSMKBffAyhLUEJnMeRj1cN4Dw+ohNXz+rEPIVTjxcbKx2KKlfpVLmMRiku1RmNNLjh4NeBuGzthsaX3djGw3zuSV/zmkewTOxZx1IPzTXgGzC3GEaUt6B0QTWxchjy3kLcD7IC1cI1XjnywgWLe4nFIp96qLPTzF11ThBgv6Dxh5IAW5MyejbKxuxeOv8cPOipRcHQTLnM5QxjnpuufnWKzfgtZU1gQK36n6UgngdNUAMUbcEKZl5ZNO/E=}
